version: '3.8'
services:
  postgres:
    image: postgres
    container_name: auth_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - '5435:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data