name: ci

on:
  push:
    branches:
      - master
      - setup/ci-cd
  pull_request:
    branches:
      - master
      - setup/ci-cd

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          DB_NAME: auth_db
          DB_PORT: 5432
          PORT: 3000
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose push
